# Generated by Django 4.2.16 on 2025-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Her", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=255)),
                ("max_attendees", models.PositiveIntegerField(default=50)),
            ],
        ),
    ]
