# Generated by Django 4.2.16 on 2025-06-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Her", "0003_eventregistration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventregistration",
            old_name="name",
            new_name="username",
        ),
    ]
